version: "3.7"
services:

  database:
    container_name: demo-storage
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  server:
    container_name: demo-server
    build: ./server-app
    volumes:
      - ./server-app:/app:rw
    ports:
      - "3000:3000"
    depends_on:
      - database

  client:
    container_name: demo-client
    build: ./client-app
    volumes:
      - ./client-app:/app:rw
    ports:
      - "4200:4200"
